site_name: Leitfaden naturnahe Regenwasserbewirtschaftung Graz
theme:
  name: material
#  custom_dir: overrides
  features:
    - navigation.expand
    - navigation.sections
#    - content.footer

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

plugins:
  - search
#  - enumerate-headings:
#      toc_depth: 3    # bis Ebene 3 nummerieren (ToC inkl.)
#      strict: true    # Fehler melden, wenn erste Überschrift nicht H1 ist
#      exclude: ["index.md",
#                "projektbeteiligte.md",
#                "kontakt.md",]
#      increment_across_pages: True

#extra:
#  generator: false

copyright: Copyright &copy; 2025 - Graz University of Technology

nav:
  - Einleitung: index.md
  - Teil 1 - Strategie und Planung auf Stadtebene:
      - Ziele dezentraler Niederschlagswasserbewirtschaftung: teil11_randbedingungen.md
      - Zielvorgaben in der Stadt Graz: teil12.md
      - Hintergrund - Wasserqualität: teil123.md
      - Hintergrund - Hydraulik und Hydrologie: teil1234.md
      - Blau-grüne Potentiale in Graz: teil11_blaugruene_potentiale.md
      - Was kann erreicht werden?: teil15.md
      - Wechselwirkungen zwischen verschiedenen Teilen der Infrastruktur: teil14.md
  - Teil 2 - Baumstandorte als Elemente der Regenwasserbewirtschaftung:
      - Ein Blick in das (virtuelle) Innere: teil21.md
      - Substrate für Baumrigolen: teil22.md
      - Schadstoffrückhalt in Baumrigolen: teil23.md
      - Fertigationstechniken bei der Baumpflanzung: teil24.md
      #- Element Umgebung: teil23.md
  - Teil 3 - Konzept und Planung:
      - Normen und Gesetze: teil3.md
#      - Baumrigolen: teil35.md
#      - Bewertung der Potenziale: teil36.md
      - Regelung zum Untergrund: teil33.md
      - Regelung zur Oberfläche: teil32.md
      - Regelung zum Bauprozess: teil34.md
      - Weiterführende Literatur: teil31.md
  - Referenzen: teil37.md
  - Projektbeteiligte: projektbeteiligte.md
  - Kontakt: kontakt.md

#document$.subscribe(({ body }) => {
#  renderMathInElement(body, {
#    delimiters: [
#      { left: "$$",  right: "$$",  display: true },
#      { left: "$",   right: "$",   display: false },
#      { left: "\\(", right: "\\)", display: false },
#      { left: "\\[", right: "\\]", display: true }
#    ],
#  })
#})